codecov:
    require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: "50...100"
    status:
        project:
            default:
                target: auto   # use base branch coverage as the target
                threshold: 2%  # the leniency in hitting the target
        patch:
            default:
                target: 70%    # require at least 70% coverage on changed lines
                threshold: 5%
